plugins {
    id 'com.gradleup.shadow' version '9.3.1'
}

repositories {
    maven { url = uri('https://hub.spigotmc.org/nexus/content/repositories/snapshots/') }
    maven { url = uri('https://oss.sonatype.org/content/repositories/snapshots') }
    maven { url = uri('https://oss.sonatype.org/content/repositories/central') }
    maven { url = uri('https://repo.codemc.org/repository/nms/') }
    maven { url = uri('https://jitpack.io') }
}

dependencies {
    implementation project(':api')

    compileOnly('org.spigotmc:spigot:1.21.11-R0.1-SNAPSHOT:remapped-mojang') {
        exclude group: 'com.mojang'
    }
    compileOnly('com.github.Rubenicos:DataFixerUpper:9.0') { transitive = false }

    compileOnly 'net.luckperms:api:5.4'

    implementation 'com.zaxxer:HikariCP:7.0.2'
    implementation 'org.mariadb.jdbc:mariadb-java-client:3.5.7'
    implementation 'com.saicone.rtag:rtag:1.5.14'
    implementation 'com.saicone.rtag:rtag-item:1.5.14'
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from(sourceSets.main.resources.srcDirs) {
        include 'plugin.yml'
        expand(rootProject.properties)
    }
}

shadowJar {
    archiveBaseName.set(rootProject.name + '-' + project.name)
    archiveClassifier.set('')

    relocate 'com.zaxxer.hikari', project.group + '.lib.hikari'
    relocate 'org.mariadb.jdbc', project.group + '.lib.mariadb'
    relocate 'com.saicone.rtag', project.group + '.lib.rtag'

    minimize {
        exclude(dependency('org.mariadb.jdbc:mariadb-java-client:.*'))
    }
}

jar {
    enabled = false
    dependsOn (shadowJar)
}