plugins {
    id 'com.gradleup.shadow' version '9.6.1'
}

repositories {
    maven { url = uri('https://hub.spigotmc.org/nexus/content/repositories/snapshots/') }
    maven { url = uri('https://repo.codemc.org/repository/nms/') }
}

dependencies {
    implementation project(':api')

    compileOnly 'org.spigotmc:spigot-api:26.2-R0.1-SNAPSHOT'

    compileOnly 'net.luckperms:api:5.4'
    compileOnly 'com.saicone:rtag:1.5.17'
    compileOnly 'com.saicone:rtag-item:1.5.17'

    implementation 'com.zaxxer:HikariCP:7.1.0'
    implementation 'org.mariadb.jdbc:mariadb-java-client:3.5.10'
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from(sourceSets.main.resources.srcDirs) {
        include 'plugin.yml'
        expand(version: project.version)
    }
}

shadowJar {
    archiveBaseName.set(rootProject.name + '-' + project.name)
    archiveClassifier.set('')
    destinationDirectory.set(file(rootProject.layout.buildDirectory.dir('libs')))

    manifest {
        attributes 'Paperweight-Mappings-Namespace': 'mojang'
    }

    relocate 'com.zaxxer.hikari', project.group + '.lib.hikari'
    relocate 'org.mariadb.jdbc', project.group + '.lib.mariadb'

    minimize {
        exclude(dependency('org.mariadb.jdbc:mariadb-java-client:.*'))
    }
}

jar {
    enabled = false
    dependsOn (shadowJar)
}